-- +goose Up
ALTER TABLE w_schedules ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('w_schedules', 'id'), COALESCE(MAX(id), 0) + 1, false) FROM w_schedules;

-- +goose Down
ALTER TABLE w_schedules ALTER COLUMN id DROP IDENTITY IF EXISTS;
