-- +goose Up
ALTER TABLE w_push_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('w_push_events', 'id'), COALESCE(MAX(id), 0) + 1, false) FROM w_push_events;

-- +goose Down
ALTER TABLE w_push_events ALTER COLUMN id DROP IDENTITY IF EXISTS;
